file(COPY "${CMAKE_CURRENT_LIST_DIR}/fonts" DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
file(COPY "${CMAKE_CURRENT_LIST_DIR}/levels" DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
file(COPY "${CMAKE_CURRENT_LIST_DIR}/shaders" DESTINATION ${CMAKE_CURRENT_BINARY_DIR})
